plugins {
    id 'org.springframework.boot' version '3.5.0'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'java'
}

group = 'com.discord'
version = '1.0'
//noinspection GrUnresolvedAccess
base {
    archivesName = 'music-bot'
}
java {
    sourceCompatibility = '25'
}

repositories {
    mavenCentral()
    maven {
        url 'https://m2.dv8tion.net/releases'
    }
    maven {
        url 'https://jitpack.io'
    }
    maven {
        url 'https://maven.lavalink.dev/releases'
    }

    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'dev.arbjerg:lavalink-client:3.4.0'
    implementation 'net.dv8tion:JDA:6.3.1'
    implementation("club.minnced:jdave-api:0.1.7")
    implementation("club.minnced:jdave-native-win-x86-64:0.1.7")
}

test {
    useJUnitPlatform()
}